name: Deploy MyST Paper

on:
  workflow_call:
    inputs:
      paper-environment-file:
        description: "Name of the paper-specific environment file (optional)"
        required: false
        type: string
        default: "paper-environment.yml"
      base_url:
        description: "Determines where the website is served from, including CSS & JS assets (needed for MyST)"
        required: false
        type: string
        default: "/${{ github.event.repository.name }}"

env:
  BASE_URL: ${{ inputs.base_url }}
  BASE_ENV_VERSION: v0.1.0

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Fetch base environment file
        run: |
          curl -fsSL https://raw.githubusercontent.com/pollomarzo/scholar-nexus-paper-config/${{ env.BASE_ENV_VERSION }}/environment.yml -o base-environment.yml

      - name: Setup Micromamba with base environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: base-environment.yml
          generate-run-shell: true
          cache-environment: true
          cache-downloads: true

      - name: Install paper-specific packages
        run: |
          if [ -f "${{ inputs.paper-environment-file }}" ]; then
            echo "Found ${{ inputs.paper-environment-file }}, installing paper-specific packages..."
            micromamba install --file ${{ inputs.paper-environment-file }} --yes
          else
            echo "No ${{ inputs.paper-environment-file }} found, skipping paper-specific packages"
          fi
        shell: micromamba-shell {0}

      - name: MyST build exports (PDF, Typst)
        run: myst build --all
        shell: micromamba-shell {0}

      - name: MyST build HTML
        run: myst build --html
        shell: micromamba-shell {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
